version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      firebase:
        patterns: ["firebase", "@firebase/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
